"""added wallet balance

Revision ID: 533567c8b541
Revises: c5ddcfb0fce5
Create Date: 2026-05-04 15:57:01.082414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533567c8b541'
down_revision: Union[str, Sequence[str], None] = 'c5ddcfb0fce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_cents', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance_cents')
    # ### end Alembic commands ###
